#writing analysis option of yaml to tell the flutter code analyser to go easy on the cose analysis as it is my first time writing the flutter code 

include: package:flutter_lints/flutter.yaml
linter: 

rules:
avoid_print: false
prefer_const_constructors-in_immutables: false
prefer_const_constructors: false 
prefer_const_literals_to_create_immutables: false
prefer_final_fields: false
unnecessary_breaks: true
use_key_in_widget_constructor: false

    
